### ISSUE TITLE
⌘-N should (configurably?) focus the input box

### ISSUE THREAD

**Issue by j6k4m8** [toggl/track-macos-feedback#47] opened 2023-03-11 14:38 UTC
## Summary

When hitting the ⌘-N shortcut to create a new item, my next action is always to edit the title and project. It would be intuitive to auto-focus the input box after hitting ⌘-N so that the user can begin typing immediately.

(Best categorized as a feature, maybe?)

- [ ] Crash 
- [x] Glitch 
- [ ] Sync 

## Steps to reproduce

1. Focus the timer application
2. Press ⌘-N

## Expected behavior

Timer title box gets focus!

## Affected versions

**App version:** 8.9.0 (2066)
**OS version:** macOS 12.6 Monterey
**Device model:** MacBook Pro 16"

**Comment by askrypnyk-toggl** [comment] 2023-03-13 07:19
Hey @j6k4m8, thanks for reaching out! 

I tried to reproduce and for me the description text field gets focused when I activate `Cmd+N` (see the screencap below) 🤔. How does the app behave for you?

https://user-images.githubusercontent.com/108934380/224632815-bdaed81f-d0c9-4986-add3-cf1b51ea764a.mov

**Comment by j6k4m8** [comment] 2023-03-13 15:51
Woah super interesting! When I press ⌘N, it looks like there's a momentary flash of focus and then it's lost. (In the video below, I click in the input to regain focus.) I have Toggl as an always-on-top window and shown by a hotkey, I wonder if those are impacting things?


https://user-images.githubusercontent.com/693511/224755083-eafb6e3d-db89-4a82-bfb2-3b691ce450fb.mp4

**Comment by askrypnyk-toggl** [comment] 2023-03-14 06:12
Hey @j6k4m8, thanks for the screen recording, it helped a lot 😀. I think I was able to reproduce what you see.

The app behaves incorrectly if you already have another time entry running when you click `Cmd+N`. If instead you stop your current time entry (`Cmd+S` should do the trick) and then click `Cmd+N` it'll work as expected.

I'll make sure the team knows about this issue and update you when we've got it fixed.

Thanks for the report 🙌

**Comment by j6k4m8** [comment] 2023-03-14 14:18
Awesome @askrypnyk-toggl!!! SO glad to hear it, and thank you!

**Comment by j6k4m8** [comment] 2023-07-18 17:51
Hi @askrypnyk-toggl, just wanted to check in on this — I've been using the web app mostly in the meantime since I can get it to respond to keyboard shortcuts consistently!

**Comment by askrypnyk-toggl** [comment] 2023-07-19 05:59
Hey @j6k4m8, thanks for the ping.

Unfortunately, no update on this one yet 😞. Can't promise it'll be fixed soon, but since it's been in the backlog for a long time, I'll bring it up with a team next time we're prioritizing issues and see if we can work on it. 

Thanks for you patience and I'm glad to hear you were able to find a workaround with the webapp 🙌

**Comment by askrypnyk-toggl** [comment] 2023-08-22 14:44
Hey @j6k4m8, wanted to go back to you on this one: it's fixed and should be released relatively soon 🙌. Look out for version 9.0.1. 

Do not hesitate to share any feedback.

**Comment by j6k4m8** [comment] 2023-08-22 15:09
Amazing, thank you for the update! Looking forward to it!

**Comment by AndrewVebster** [comment] 2023-08-25 15:37
Just wanted to let you know that version 9.0.1 is now live 🙌 

I'm closing the issue but if it's still not fixed for you, feel free to reopen it again.

**Closed by AndrewVebster** 2023-08-25 15:37 UTC
Labels: bug

**Comment by j6k4m8** [comment] 2023-08-25 17:02
Appears to be working — woohoo!!!
